[versions]
agp = "8.9.3"
junit = "4.13.2"
supportTestRunner = "1.0.2"
supportEspressoCore = "3.0.2"
appcompat7 = "28.0.0"
material = "1.12.0"
androidxJunit = "1.2.1"
androidxEspressoCore = "3.6.1"
appcompat = "1.7.0"
constraintlayout = "2.2.0"
fragment = "1.8.5"
recyclerview = "1.3.2"
swiperefreshlayout = "1.1.0"
kotlin = "2.2.21"
foundation = "1.9.4"
ksp = "2.2.21-2.0.4"
hiltAndroid = "2.57.2"
hiltAndroidCompiler = "2.57.2"
hiltNavigationCompose = "1.3.0"
litert = "1.4.1"



[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
support-test-runner = { group = "com.android.support.test", name = "runner", version.ref = "supportTestRunner" }
support-espresso-core = { group = "com.android.support.test.espresso", name = "espresso-core", version.ref = "supportEspressoCore" }
appcompat-v7 = { group = "com.android.support", name = "appcompat-v7", version.ref = "appcompat7" }
support-v4 = { module = "com.android.support:support-v4", version.ref = "appcompat7" }
support-annotations = { module = "com.android.support:support-annotations", version.ref = "appcompat7" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
litert = { module = "com.google.ai.edge.litert:litert", version.ref = "litert" }
litert-gpu-api = { module = "com.google.ai.edge.litert:litert-gpu-api", version.ref = "litert" }
litert-gpu = { module = "com.google.ai.edge.litert:litert-gpu", version.ref = "litert" }
litert-support = { module = "com.google.ai.edge.litert:litert-support", version.ref = "litert" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }


[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
dagger-hilt = {id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid"}
